# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad02a80fb0f0665c20b6927f0011d033810e9582c363e05e60881fb4cf08a3162d1aa1cf061084234d8b0b0d5420c7668aed3b0f11cc61eac8271ed82da3a8ab

test:
  secret_key_base: 7b855c508512b2b6f9e2cfb0e3634882310af72b3bad064f196e7f6b7c60ab1d742d0744de00f4ada0f6a39b25f23b32e471f58d719c2e65a2c1671498b6396e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
